### ISSUE TITLE
Tags with comma

### ISSUE THREAD

**Issue by JSoko** [janis91/nextnotes#14]
# Bug report, perhaps Feature request
## Expected Behavior

IMHO best behavior would be to understand it as two tags
2nd posibillity would be to under stand it as one tag
`versuch, Test`

## Current Behavior
Its be manageged and shown in the left panel as one tag
but under the note it is shown as two tags
```
versuch
Test

```

Searching for 
#versuch, Test#
doesn't find the note, also if You just click on the Tag

## Possible Solution
Handle commas in tags right; as separator, or as character...

## Context
If entering Tags, it would be easier to be able to enter 2 or more tags separated bei a comma or an other charakter.
## Your Environment

* Next Notes version used:
1.0.0 from stable 10 08/30/2016
* Browser Name and version:
Firefox 48.02
* Operating System and version (desktop or mobile):
desktop Win10
* ownCloud/nextcloud version: (see ownCloud admin page or version.php)
Nextcloud 9.1.0.16 aka 10.0.0
* PHP version
7.0.8-0ubuntu0.16.04.2
* Database version
mysql  Ver 15.1 Distrib 10.0.25-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2
* Are you using encryption: yes/no
no
## Log File Contentv (nextcloud/owncloud.log of the "data"-directory)
nothing relevant to this issue

**Comment by janis91** [comment]
Thank you for testing. It's a bug. I know how to reproduce it and will have a look into it, asap. I prefer the 2nd expected behaviour, because the tag syntax should allow as much signs as possible (only "#" is restricted). Maybe there is a use case for tags containing commas.

The 2nd issue is the adding of multiple tags quickly. I will see what is possible here.

**Comment by janis91** [comment]
OK, I got a fix now. The future behaviour will be like the following:
Characters not allowed in tags: "#" and ","
Tagsearch works like before: #tagtitle# will search for the tagtitle. If you want to add another tag you can add another #tagtitle2# in the search input field.
Also the possiblity to quickly add multiple tags is now supported.
