### ISSUE TITLE
embedding images

### ISSUE THREAD

**Issue by JSoko** [janis91/nextnotes#19]
# Bug report
## Expected Behavior
Embed image and see it in your note

## Current Behavior
The code looks good, but the image is not shown

## Steps to Reproduce (for bugs)
create a note:
```
Bild einbetten

![1](https://www.sokolowski.org/wp-content/uploads/2010/04/js200.jpg)
![2](http://unfallflucht.eu/g/magnifier2-gray.gif)
Seite Ende
```

save it and switch to the Preview
the images should be embedded, but they are not shown.

http://u.of99.de/21

## Your Environment
* Next Notes version used:
actual
* Browser Name and version:
Firefox 48.2 and Chrome  52.0.2743.116 m
* Operating System and version (desktop or mobile):
Win 10
* ownCloud/nextcloud version: (see ownCloud admin page or version.php)
Nextcloud 9.1.0.16 aka 10.0.0
* PHP version
PHP version 7.0.8-0ubuntu0.16.04.2
* Database version
 mysql Ver 15.1 Distrib 10.0.25-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2
* Are you using encryption: yes/no

## Site-Output
```
<div id="app-navigation">
<div id="app-content" style="transition: all 0.3s ease 0s;">
<div id="app-navigation-toggle" class="icon-menu" style="display:none;"></div>
<div id="app-content-wrapper">
<div id="nextnotes-editor">
<form>
<textarea id="nextnotes-textarea" style="display: none;"></textarea>
<div class="editor-toolbar disabled-for-preview">
<div class="CodeMirror cm-s-paper CodeMirror-wrap">
<div style="overflow: hidden; position: relative; width: 3px; height: 0px; top: 15px; left: 15px;">
<div class="CodeMirror-vscrollbar" cm-not-content="true">
<div class="CodeMirror-hscrollbar" cm-not-content="true">
<div class="CodeMirror-scrollbar-filler" cm-not-content="true"></div>
<div class="CodeMirror-gutter-filler" cm-not-content="true"></div>
<div class="CodeMirror-scroll" tabindex="-1" draggable="true">
<div class="editor-preview editor-preview-active">
<p>Bild einbetten</p>
<p>
<img alt="1" src="https://www.sokolowski.org/wp-content/uploads/2010/04/js200.jpg">
<br>
<img alt="2" src="http://unfallflucht.eu/g/magnifier2-gray.gif">
<br>
Seite Ende
</p>
</div>
</div>
<div class="editor-preview-side"></div>
<div class="editor-statusbar">
</form>
```

**Comment by janis91** [comment]
Yes, it's because of the following reason:

> Refused to load the image because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".

Currently i am not aware of a solution to this. I have to get further information about this Content Security Policy and how to avoid this..

**Comment by JSoko** [comment]
perhaps that helps:

https://github.com/owncloud/files_pdfviewer/issues/63

> After digging a little more into Lukas' post, I was able to solve it. You just need to edit the ../owncloud/apps/files_pdfviewer/controller/displaycontroller.php file and add:
> 
> $policy->addAllowedImageDomain('*');
> 
> as shown in this post: b46d2cf
>
