### ISSUE TITLE
FR: Embed Images stored in Nextcloud

### ISSUE THREAD

**Issue by JSoko** [janis91/nextnotes#20]
#Featurerequest
As we can store images in Nextcloud, wouldn't it be easy, to be able just to link to images stored in the Nextcloud per markdown.

By now, you ownly can link to images witch have a public link

**Comment by janis91** [comment]
Yes and No: Internally it could make sense to include an image in a private note. But when you share it in a future version it isn't good (or maybe even possible) to display an image which isn't shared. As this is a potential cause of bugs and inconsistencies I'll have to evaluate this request in the future. For now the sharing solution is an acceptable workaround, I would say.

**Comment by janis91** [comment]
I will close this issue:
The common procedure for linking a picture from the nextcloud should be like the following:

1. If you want to share a note to another user OR externally in a future update you have to make sure, that the image is also available as a public link.

2. If you don't want to share the note and just have it in your own account, it is possible to link it like follows:
`https://demo.nextcloud.com/remote.php/webdav/Demo%20Image%20-%20ccc.jpg`
as an example from the nextcloud demo. You can always use this kind of link when you are logged in.

This should be a good solution. All other solutions will potentially pervert the security of files (images) in nextcloud.

**Comment by xephon2** [comment]
I'd like to create notes within Nextcloud and locally. Your approach would mean, I'd need to convert all image references in my local notes, that are synced with Nextcloud. But I'd like to edit and read my notes, if  the Nextcloud server is not availabe, e.g. when sitting in a train. Please reopen this feature request.
