### ISSUE TITLE
Translation setup

### ISSUE THREAD

**Issue by janis91** [janis91/nextnotes#26]
setup for transifex required.

**Comment by janis91** [comment]
@morrisjobke

**Comment by MorrisJobke** [comment]
@janis91 Could you assign me to this issue?

**Comment by MorrisJobke** [comment]
> @janis91 Could you assign me to this issue?

And can you give @nextcloud-bot contributor rights - so the bot can push the changes ;)

**Comment by MorrisJobke** [comment]
> @janis91 Could you assign me to this issue?

I guess you need to add me as contributor before you can assign me.

**Comment by MorrisJobke** [comment]
@janis91 Thanks :)

**Comment by janis91** [comment]
@MorrisJobke you're welcome :)

**Comment by janis91** [comment]
Just in order to get things clarified for me: Do you need more input from my side, like a configuration file for transifex or something like that? If so please just poke. Ty

**Comment by MorrisJobke** [comment]
> Do you need more input from my side, like a configuration file for transifex or something like that?

Nope. I have everything :)

**Comment by janis91** [comment]
Hi, I just want to poke and kindly ask if this is still in your mind? :-)

**Comment by MorrisJobke** [comment]
Done :)

https://www.transifex.com/nextcloud/nextcloud/nextnotes/

Daily script will run every night at ~3 o'clock CET. 😉
