### ISSUE TITLE
apps.nextcloud.com

### ISSUE THREAD

**Issue by JSoko** [janis91/nextnotes#29]
There is no Appname in the Appstore and the Font used on the descriptionssite ist to big

![appname](https://cloud.githubusercontent.com/assets/5583290/18636550/87289fa2-7e89-11e6-9c3d-007fe5d1ab90.jpg)
![beschreibung](https://cloud.githubusercontent.com/assets/5583290/18636549/870b0302-7e89-11e6-9601-9ece0e52b375.jpg)

**Comment by janis91** [comment]
I uploaded a new Version. The description is a little ugly but not as much as before. Hope it works now.. Probanly it is a bug of the appstore, too. Because I don't think there should be no fallback, if a translation is not given.. I will link this to an bug report in nextcloud/appstore.

**Comment by JSoko** [comment]
The missing Appname is now fixed.

The app-description is now better but in a box with bad wordwrapping...
...on OCR the description seems to be OK.

**Comment by janis91** [comment]
the next update will display everything correctly. Its already in the master branch. Closed.
