### ISSUE TITLE
v 0.91 breaks Nextcloud apps and isn't shown in any category

### ISSUE THREAD

**Issue by JSoko** [janis91/nextnotes#31]
# Bug report
## Expected Behavior
After copying to /nextcloud/apps Next Notes should be shown in /settings/apps?category=disabled#
and
under a category, p.e. /settings/apps?category=productivity#

## Current Behavior
/settings/apps?category=disabled# or /settings/apps?category=enabled# (when enabled) loads forever as long as Next Notes 0.91 is in the /apps directory

## Steps to Reproduce (for bugs)
1. remove apps/nextnotes
2. remove nextnotes own Databasentries and under oc_appconfig 
3. restart apache server
4. /settings/apps?category=disabled# and  /settings/apps?category=enabled# working as it should
5. copy nextnotes 0.91 to /apps
6. sudo chown -R www-data:www-data /var/www/NNN/apps
7.  sudo -u www-data php occ app:list
8.  sudo -u www-data php occ app:enable nextnotes
9. login to Nextcloud as admin
10. create a note
11. head over to /settings/apps?category=enabled# -> loading forever, head over to /settings/apps?category=disabled# -> works as expected,  Mutimedia, Productivity, Game and Tool work as expected, but don't show Next Notes
While loading forever in the console
```
TypeError: t.charAt is not a function
	c = t.charAt(x);
```
is shown
12. sudo -u www-data php occ app:disable nextnotes
13. nextnotes now is deactivated, but head over to /settings/apps?category=enabled# -> loading forever, head over to /settings/apps?category=disabled# -> works as expected,  Mutimedia, Productivity, Game and Tool work as expected, but don't show Next Notes
14. rm nextnotes -r
15. service apache2 restart ->every thing works as expected

## Your Environment

* Next Notes version used:
0.91
* Browser Name and version:
Firefox 48
* Operating System and version (desktop or mobile):
* ownCloud/nextcloud version: (see ownCloud admin page or version.php)
10.0.16
* PHP version
7
* Database version
MariaDB
* Are you using encryption: yes/no
No

## Log File Contentv (nextcloud/owncloud.log of the "data"-directory)
Nothing realy related, perhaps
```
Error	PHP	Array to string conversion at .../settings/Controller/AppSettingsController.php#238
Error	PHP	Array to string conversion at .../settings/Controller/AppSettingsController.php#239
Error	PHP	Array to string conversion at .../settings/Controller/AppSettingsController.php#239

```

**Comment by janis91** [comment]
Which archive did you download? The archive from the appstore or the release archive from github? I will look into this on next weekend. Hopefully I can reproduce it ;-)

**Comment by JSoko** [comment]
The archive vom the appstore
https://github.com/janis91/nextnotes/releases/download/v0.9.1-beta/nextnotes-0.9.1-beta.tar.gz
Shall I try this one too? https://github.com/janis91/nextnotes/releases/download/v0.9.1-beta/nextnotes-0.9.1-beta.tar.gz

**Comment by JSoko** [comment]
Btw: I didn't copy pax_global_header to the /apps/ directory. Could this be my fault?

**Comment by JSoko** [comment]
Just downloadeed the archive from the github. Removed nextnotes directory under /apps
copied the directory to apps, restarted apache and I have the forever-loading under /settings/apps?category=disabled# again.

Removing the /apps/nextcloud directory and restarting apache2 leads to working as expected...

**Comment by janis91** [comment]
Ok somethign is wrong with the package and / or the installation of the app. i will have a look into that.

**Comment by janis91** [comment]
As it is definitely a bug in nextcloud and not the fault of anything in nextnotes, I will close this issue. Please have a look at [Bug: info.xml interpretation not the latest](https://github.com/nextcloud/server/issues/1466). Hopefully this will be updated soon.

**Comment by JSoko** [comment]
Fix: https://github.com/nextcloud/server/pull/1586#issuecomment-250715110

**Comment by janis91** [comment]
https://help.nextcloud.com/t/blank-page-on-enabled-apps-after-installing-ocr-1-0-0/5812/5?u=janis91
